version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      vpcbr:
        ipv4_address: 10.10.10.100

  client:
    build: .
    command: sleep 1h
    environment:
      VAULT_ADDR: http://nginx:8200
    networks:
      vpcbr:
        ipv4_address: 10.10.10.101

  vault1:
    build: .
    command: vault server -config /vault/config.hcl
    environment:
      VAULT_ADDR: http://localhost:8200
    networks:
      vpcbr:
        ipv4_address: 10.10.10.10
    volumes:
      - ./config.hcl:/vault/config.hcl
  vault2:
    build: .
    command: vault server -config /vault/config.hcl
    environment:
      VAULT_ADDR: http://localhost:8200
    networks:
      vpcbr:
        ipv4_address: 10.10.10.2
    volumes:
      - ./config.hcl:/vault/config.hcl
  vault3:
    build: .
    command: vault server -config /vault/config.hcl
    environment:
      VAULT_ADDR: http://localhost:8200
    networks:
      vpcbr:
        ipv4_address: 10.10.10.3
    volumes:
      - ./config.hcl:/vault/config.hcl
  vault4:
    build: .
    environment:
      VAULT_ADDR: http://localhost:8200
    command: vault server -config /vault/config.hcl
    networks:
      vpcbr:
        ipv4_address: 10.10.10.4
    volumes:
      - ./config.hcl:/vault/config.hcl

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/24
         gateway: 10.10.10.1
